version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vlm-ocr-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_ENDPOINT=https://api.openai.com/v1
        - NEXT_PUBLIC_API_KEY=sk-your-api-key-here
        - NEXT_PUBLIC_API_NAME=Default-API
        - NEXT_PUBLIC_DEFAULT_MODEL=gpt-4o
        - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
        - NEXT_PUBLIC_MODEL_OPTIONS=["gpt-4o","gpt-4.1"]
        - NEXT_PUBLIC_DEFAULT_PROVIDER=OpenAI
    container_name: vlm-ocr-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  backend_data:
    driver: local